---
title: "simple_quarto_website"
bibliography: reference.bib
---
# DSAN 5000 - Lab-1.2 
A simple quarto website for **DSAN 5000 : Data Science and Analytics** lab-1.2.

## Course Description
This course introduces students to several core data science concepts. It teaches students how to synthesize disparate, possibly unstructured data to better understand and characterize the world, and in some cases, to draw meaningful inferences. Topics covered include: the history of data science, successes and failures in data analytics, the data analytics life cycle, data/web scraping and APIs, data wrangling, data characterization (correlations, identifying clusters and associations), data inference and basic machine learning, network analysis, data ethics, and visual analytics. Students will work on a semester-long data science project that starts with question formulation and data collection, and goes through all the stages of the life cycle, culminating in data storytelling. The course also maps data science case studies to topics presented throughout the semester.[^1]

### Prerequisites
- Intermediate coding experience in Python3
-  Knowledge of introductory statistics

### Table
| Assignment| Due Date | Status|
| :--------:| :-------:| :----:|
| Assignment 1 | 09/14/2024 | Published |
| Assignment 2 | 09/09/2024 | Graded |

### Columns
::: {layout-ncol=2}
#### Assignments
  Assignment 1 \
  Assignment 2 
  
#### Due Date
  14-09-2024 \
  09/09/2024
:::

## Math Equations
### LaTex Equation (Inline)
The conditioanl probability $Pr(A \mid B) = \frac{Pr(A \cap B)}{Pr(B)}$

### LaTex Equation (Non Inline)
$$Pr(A \mid B) = \frac{Pr(A \cap B)}{Pr(B)}$$